Feature/pim 1700 verified grain yield summary grid UI
bcgov/nr-brmb-pim pull request #155
Opened 2024-12-23 20:22 UTC by vivid-esnauffer

2025-01-01 00:07 UTC, mhostett requested changes

2025-01-01 00:07 UTC, mhostett commented on cirras-underwriting-war/cirras-underwriting-war/src/main/angular/src/app/components/verified-yield/summary-list/verified-yield-summary-list.component.html
> +    <div class="header border-top border-bottom border-right">
I noticed that there is an additional column (Historical) in the mockup but it's nowhere else mentioned. I added a comment to the ticket for Andrew. Thought I mention it here as well so we don't forget.

2025-01-01 00:07 UTC, mhostett commented on cirras-underwriting-war/cirras-underwriting-war/src/main/angular/src/app/components/verified-yield/summary/verified-yield-summary.component.ts
> +        // TODO: insuread acres is missing
I added it to the PIM-1808 branch

2025-01-01 00:07 UTC, mhostett commented on cirras-underwriting-war/cirras-underwriting-war/src/main/angular/src/app/conversion/models-yield.ts
> +  export interface VerifiedYieldSummary {
insured acres needs to be added once it's ready

2025-01-02 23:53 UTC, vivid-esnauffer commented
This will be merged into feature 3.7.0

2025-01-02 23:53 UTC, closed without merging